name: Cypress End-to-end Regression Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 15 */14 * 4'  # 10 AM CST every other Thursday

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # browser: chrome
          # headed: false
          command: npm run test:regression

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Reports
          path: cypress/reports/html/index.html
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`