name: Cypress End-to-end Smoke Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 13 * * *'      # Daily at 7:00 AM UTC

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install npm dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # browser: chrome
          # headed: false
          command: npm run test:smoke